vulkan: true                  # The Vulkan renderer is not yet implemented
v-sync: false                 # To run or not to run in V-Sync mode
msaa-samples: 16              # Multisampling sample count
