name: Deploy to pages
on:
  push:
    branches: ["master"]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: true
      - name: Checkout submodules
        shell: bash
        run: |
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
      - uses: actions/setup-node@v4
        with:
          node-version: '16'
      - run: sudo apt update && sudo apt-get install x11-xserver-utils libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev gcc make g++ libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libvulkan1 mesa-vulkan-drivers vulkan-tools libvulkan-dev libasound2-dev libflac-dev libogg-dev libtool libvorbis-dev libopus-dev libsndfile1-dev libglew-dev libssl-dev zlib1g zlib1g-dev libglfw3 libglfw3-dev libyaml-cpp-dev libxkbcommon-dev
      - run: npm install -g terser
      - run: npm install -g csso-cli
      - run: npm install -g html-minifier
      - run: find ./ -type f -iname "*.js" -exec terser {} --compress -o {} \;
      - run: find ./ -type f -iname "*.css" -exec csso {} -o {} \;
      - uses: mymindstorm/setup-emsdk@v14
      - run: "emcc -v"
      - name: Compile project
        run: |
          git clone https://github.com/MadLadSquad/UntitledImGuiFramework.git --recursive
          cd UntitledImGuiFramework || exit
          ./install.sh ci || exit
          cd UVKBuildTool/build || exit
          ./UVKBuildTool --generate ../../../ || exit
          cd ../../../ || exit
          mkdir build && cd build
          emcmake cmake .. -DCMAKE_BUILD_TYPE=RELEASE || exit
          make -j "$(grep -c processor /proc/cpuinfo)" || exit
          mv UImGuiDemo.html index.html
          mv ../Config/WASM/* .
          cd ../ || exit
      - name: Copy files and clean up
        run: |
          cd build || exit
          rm -rf CMake* CPack* Framework/ Makefile cmake_* test_fs_support* lib*.a compile_commands.json
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          # Upload entire repository
          path: './build'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
